In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('train.csv')
data.dropna(inplace=True)
data = data.drop('ID',axis=1)
data_test = pd.read_csv('test.csv')
data_test = data_test.drop('ID',axis=1)

In [3]:
data.shape, data_test.shape

((9000, 18), (3330, 17))

In [5]:
# np.all(data_test['ID'] == np.arange(data_test.shape[0]))

In [6]:
data['Administrative'].value_counts()
data['Administrative_Present'] = np.int32(data['Administrative'] != 0)
data_test['Administrative_Present'] = np.int32(data_test['Administrative'] != 0)

In [7]:
data.head()

Administrative  Administrative_Duration  Informational  \
0               2                    208.0              1   
1               1                      0.0              0   
2               0                      0.0              1   
3               0                      0.0             16   
4               1                      7.0              0   

   Informational_Duration  ProductRelated  ProductRelated_Duration  \
0               50.000000              30              1461.666667   
1                0.000000               1                 0.000000   
2             1729.000000              19              1401.083333   
3             1210.397619               5               279.857143   
4                0.000000              50              2330.727381   

   BounceRates  ExitRates  PageValues  SpecialDay  Month  OperatingSystems  \
0     0.000000   0.021250         0.0         0.0      1                 1   
1     0.200000   0.200000         0.0         0.6      2                 3   
2     0.020000   0.050000         0.0         0.0      9                 1   
3     0.003175   0.012764         0.0         0.0      1                 1   
4     0.023810   0.031399         0.0         0.0      8                 5   

   Browser  Region  TrafficType  VisitorType  Weekend  Revenue  \
0        7       0           12            2        0        0   
1        3       2            4            2        0        0   
2       10       0           12            2        0        0   
3       10       0           11            2        0        0   
4       10       6           12            2        0        0   

   Administrative_Present  
0                       1  
1                       1  
2                       0  
3                       0  
4                       1

In [8]:
data_test.head()

Administrative  Administrative_Duration  Informational  \
0               0                      0.0              0   
1               0                      0.0              0   
2               0                      0.0              0   
3               0                      0.0              5   
4               0                      0.0              0   

   Informational_Duration  ProductRelated  ProductRelated_Duration  \
0                0.000000             141              2886.523521   
1                0.000000               8                64.000000   
2                0.000000              15               139.833333   
3              497.833333              26               851.666667   
4                0.000000              31               822.650000   

   BounceRates  ExitRates  PageValues  SpecialDay  Month  OperatingSystems  \
0     0.004317   0.018798         0.0         0.8      2                 1   
1     0.000000   0.050000         0.0         0.0      9                 1   
2     0.026667   0.053333         0.0         0.0      1                 1   
3     0.006452   0.018280         0.0         0.0      8                 1   
4     0.020690   0.020805         0.0         1.0      2                 3   

   Browser  Region  TrafficType  VisitorType  Weekend  Administrative_Present  
0       10       2           12            2        0                       0  
1       10       6           11            1        0                       0  
2       10       1            8            2        0                       0  
3       10       0            4            1        1                       0  
4        3       6            7            2        1                       0

In [9]:
data['Informational'].value_counts()
data['Informational_Present'] = np.int32(data['Informational'] != 0)
data_test['Informational_Present'] = np.int32(data_test['Informational'] != 0)

In [10]:
data['ProductRelated_Duration'].value_counts()
data['ProductRelated_Duration_Present'] = np.int32(data['ProductRelated_Duration'] != 0)
data_test['ProductRelated_Duration_Present'] = np.int32(data_test['ProductRelated_Duration'] != 0)

In [11]:
data['BounceRates'].value_counts()
data['BounceRates_Present'] = np.int32(data['BounceRates'] != 0)
data_test['BounceRates_Present'] = np.int32(data_test['BounceRates'] != 0)

In [12]:
data['PageValues'].value_counts()
data['PageValues_Present'] = np.int32(data['PageValues'] != 0)
data_test['PageValues_Present'] = np.int32(data_test['PageValues'] != 0)

In [13]:
data['SpecialDay'].value_counts()
data['SpecialDay_Present'] = np.int32(data['SpecialDay'] != 0)
data_test['SpecialDay_Present'] = np.int32(data_test['SpecialDay'] != 0)

In [14]:
data['OperatingSystems'].value_counts()

1    4826
3    1931
5    1835
0     328
4      55
7      14
6       6
2       5
Name: OperatingSystems, dtype: int64

In [15]:
data['OS1'] = data['OperatingSystems']==1
data['OS3'] = data['OperatingSystems']==3
data['OS5'] = data['OperatingSystems']==5
data['OS0'] = data['OperatingSystems']==0
data.loc[data['OperatingSystems']==1,'OperatingSystems'] = 0
data.loc[data['OperatingSystems']==3,'OperatingSystems'] = 0
data.loc[data['OperatingSystems']==5,'OperatingSystems'] = 0
data.loc[data['OperatingSystems']==0,'OperatingSystems'] = 0

data_test['OS1'] = data_test['OperatingSystems']==1
data_test['OS3'] = data_test['OperatingSystems']==3
data_test['OS5'] = data_test['OperatingSystems']==5
data_test['OS0'] = data_test['OperatingSystems']==0
data_test.loc[data_test['OperatingSystems']==1,'OperatingSystems'] = 0
data_test.loc[data_test['OperatingSystems']==3,'OperatingSystems'] = 0
data_test.loc[data_test['OperatingSystems']==5,'OperatingSystems'] = 0
data_test.loc[data_test['OperatingSystems']==0,'OperatingSystems'] = 0

In [16]:
data['Browser'].value_counts()

10    5792
3     1820
1      532
7      337
8      122
4      121
11     103
9       78
5       43
6       38
2        8
12       5
0        1
Name: Browser, dtype: int64

In [17]:
data['B10'] = data['Browser'] == 10
data['B3'] = data['Browser'] == 3
data['B1'] = data['Browser'] == 1
data['B7'] = data['Browser'] == 7
data['B8'] = data['Browser'] == 8
data['B4'] = data['Browser'] == 4
data['B11'] = data['Browser'] == 11

data.loc[data['Browser'] == 10,'Browser'] = 0
data.loc[data['Browser'] == 3,'Browser'] = 0
data.loc[data['Browser'] == 1,'Browser'] = 0
data.loc[data['Browser'] == 7,'Browser'] = 0
data.loc[data['Browser'] == 8,'Browser'] = 0
data.loc[data['Browser'] == 4,'Browser'] = 0
data.loc[data['Browser'] == 11,'Browser'] = 0

data_test['B10'] = data_test['Browser'] == 10
data_test['B3'] = data_test['Browser'] == 3
data_test['B1'] = data_test['Browser'] == 1
data_test['B7'] = data_test['Browser'] == 7
data_test['B8'] = data_test['Browser'] == 8
data_test['B4'] = data_test['Browser'] == 4
data_test['B11'] = data_test['Browser'] == 11

data_test.loc[data_test['Browser'] == 10,'Browser'] = 0
data_test.loc[data_test['Browser'] == 3,'Browser'] = 0
data_test.loc[data_test['Browser'] == 1,'Browser'] = 0
data_test.loc[data_test['Browser'] == 7,'Browser'] = 0
data_test.loc[data_test['Browser'] == 8,'Browser'] = 0
data_test.loc[data_test['Browser'] == 4,'Browser'] = 0
data_test.loc[data_test['Browser'] == 11,'Browser'] = 0

In [18]:
data['Region'].value_counts()

0    3512
6    1765
2     879
5     813
1     582
3     532
4     378
7     313
8     226
Name: Region, dtype: int64

In [19]:
data['TrafficType'].value_counts()

4     2841
8     1826
12    1484
7      791
14     521
2      323
5      321
11     250
3      202
15     178
18     144
19      31
10      31
13      27
1       10
16       8
6        8
17       2
9        1
0        1
Name: TrafficType, dtype: int64

In [20]:
data['T4'] = data['TrafficType']==4
data['T8'] = data['TrafficType']==8
data['T12'] = data['TrafficType']==12
data['T7'] = data['TrafficType']==7
data['T14'] = data['TrafficType']==14
data['T2'] = data['TrafficType']==2
data['T5'] = data['TrafficType']==5
data['T11'] = data['TrafficType']==11
data['T3'] = data['TrafficType']==3
data['T15'] = data['TrafficType']==15
data['T18'] = data['TrafficType']==18

data.loc[data['TrafficType']==4,'TrafficType'] = 0
data.loc[data['TrafficType']==8,'TrafficType'] = 0
data.loc[data['TrafficType']==12,'TrafficType'] = 0
data.loc[data['TrafficType']==7,'TrafficType'] = 0
data.loc[data['TrafficType']==14,'TrafficType'] = 0
data.loc[data['TrafficType']==2,'TrafficType'] = 0
data.loc[data['TrafficType']==5,'TrafficType'] = 0
data.loc[data['TrafficType']==11,'TrafficType'] = 0
data.loc[data['TrafficType']==3,'TrafficType'] = 0
data.loc[data['TrafficType']==15,'TrafficType'] = 0
data.loc[data['TrafficType']==8,'TrafficType'] = 0

data_test['T4'] = data_test['TrafficType']==4
data_test['T8'] = data_test['TrafficType']==8
data_test['T12'] = data_test['TrafficType']==12
data_test['T7'] = data_test['TrafficType']==7
data_test['T14'] = data_test['TrafficType']==14
data_test['T2'] = data_test['TrafficType']==2
data_test['T5'] = data_test['TrafficType']==5
data_test['T11'] = data_test['TrafficType']==11
data_test['T3'] = data_test['TrafficType']==3
data_test['T15'] = data_test['TrafficType']==15
data_test['T18'] = data_test['TrafficType']==18

data_test.loc[data_test['TrafficType']==4,'TrafficType'] = 0
data_test.loc[data_test['TrafficType']==8,'TrafficType'] = 0
data_test.loc[data_test['TrafficType']==12,'TrafficType'] = 0
data_test.loc[data_test['TrafficType']==7,'TrafficType'] = 0
data_test.loc[data_test['TrafficType']==14,'TrafficType'] = 0
data_test.loc[data_test['TrafficType']==2,'TrafficType'] = 0
data_test.loc[data_test['TrafficType']==5,'TrafficType'] = 0
data_test.loc[data_test['TrafficType']==11,'TrafficType'] = 0
data_test.loc[data_test['TrafficType']==3,'TrafficType'] = 0
data_test.loc[data_test['TrafficType']==15,'TrafficType'] = 0
data_test.loc[data_test['TrafficType']==8,'TrafficType'] = 0

In [21]:
data['VisitorType'].value_counts()
data['V1'] = data["VisitorType"] ==1
data['V2'] = data["VisitorType"] ==2 
data['V0'] = data["VisitorType"] ==0 
data = data.drop('VisitorType',axis=1)

data_test['VisitorType'].value_counts()
data_test['V1'] = data_test["VisitorType"] ==1
data_test['V2'] = data_test["VisitorType"] ==2 
data_test['V0'] = data_test["VisitorType"] ==0 
data_test = data_test.drop('VisitorType',axis=1)

In [25]:
data.shape, data_test.shape

((9000, 49), (3330, 48))

In [24]:
data['Weekend'].value_counts()
data['W1'] = data['Weekend']==1
data['W2'] = data['Weekend']==0
data = data.drop('Weekend',axis=1)

data_test['W1'] = data_test['Weekend']==1
data_test['W2'] = data_test['Weekend']==0
data_test = data_test.drop('Weekend',axis=1)

In [71]:
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import train_test_split

x = data.drop(['Revenue'], axis = 1)
y = data['Revenue']

x = np.array(x).astype(np.float32)
x_test = np.array(data_test)
# for i in range(x.shape[1]):
# 	if (np.max(x[:,i]) - np.min(x[:,i]))!=0 :
# 		x[:,i] = (x[:,i] - np.min(x[:,i]))/(np.max(x[:,i]) - np.min(x[:,i]))
# # 		x_test[:,i] = (x_test[:,i] - np.min(x_test[:,i]))/(np.max(x_test[:,i]) - np.min(x_test[:,i]))
y = np.array(y).astype(np.float32)

x_train, x_val, y_train, y_val = train_test_split(x, y, test_size = 0.2, random_state = 0)

print(x_val.shape)

from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor(n_estimators=300,random_state=420)
model.fit(x_train,y_train)
yh_val = model.predict(x_val)
print("AUC of Random Forest Regressor: ",roc_auc_score(y_val,yh_val))


(1800, 48)
AUC of Random Forest Regressor:  0.9261368190364089


In [61]:
imp_feats = np.argsort(model.feature_importances_)
model.feature_importances_[imp_feats]

array([1.47731135e-04, 4.98236412e-04, 6.21238940e-04, 8.04486811e-04,
       8.16679202e-04, 1.07815752e-03, 1.22254380e-03, 1.49628557e-03,
       1.52936574e-03, 1.62972967e-03, 1.66931230e-03, 1.77723462e-03,
       2.03238248e-03, 2.06230799e-03, 2.08343307e-03, 2.11700414e-03,
       2.34511836e-03, 2.34853623e-03, 2.70001839e-03, 2.81313401e-03,
       2.84367359e-03, 3.06349064e-03, 3.56985102e-03, 3.88074494e-03,
       3.99468422e-03, 4.00988580e-03, 4.03931720e-03, 4.11331253e-03,
       4.20838064e-03, 4.39957279e-03, 4.41810707e-03, 4.54409294e-03,
       4.60295980e-03, 5.02628293e-03, 5.57284005e-03, 5.89667227e-03,
       6.77330044e-03, 1.19853810e-02, 2.27805803e-02, 2.38380143e-02,
       3.73259456e-02, 4.17903581e-02, 4.90424974e-02, 6.96752165e-02,
       7.20704413e-02, 7.40557313e-02, 7.66548303e-02, 4.14030899e-01])

In [62]:
x_train_imp = x_train[:,imp_feats[-5:]]
x_val_imp = x_val[:,imp_feats[-5:]]
x_test_imp = x_test[:,imp_feats[-5:]]

In [63]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(3)
x_train_imp = poly.fit_transform(x_train_imp)
x_val_imp = poly.fit_transform(x_val_imp)
x_test_imp = poly.fit_transform(x_test_imp)

In [64]:
x_train = np.concatenate((x_train,x_train_imp),axis=1)
x_test = np.concatenate((x_test,x_test_imp),axis=1)
x_val = np.concatenate((x_val,x_val_imp),axis=1)

In [65]:
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor(n_estimators=300,random_state=420)
model.fit(x_train,y_train)
yh_val = model.predict(x_val)
print("AUC of Random Forest Regressor: ",roc_auc_score(y_val,yh_val))

AUC of Random Forest Regressor:  0.9229044675837401


In [66]:
imp_feats = np.argsort(model.feature_importances_[49:])
imp_feats = imp_feats[-3:]

In [67]:
imp_feats

array([19,  7, 34])

In [68]:
x_train_imp = x_train_imp[:,imp_feats]
x_val_imp = x_val_imp[:,imp_feats]
x_test_imp = x_test_imp[:,imp_feats]

In [69]:
x_train = np.concatenate((x_train,x_train_imp),axis=1)
x_test = np.concatenate((x_test,x_test_imp),axis=1)
x_val = np.concatenate((x_val,x_val_imp),axis=1)

In [70]:
x_train.shape,x_val.shape

((7200, 107), (1800, 107))

array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)